### ISSUE TITLE
(WIKI) Integration with AngularFire2 not working

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#1050]
**Steps to reproduce and a minimal demo of the problem**
Follow the steps in https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2

**Current behavior**
When trying to ```npm start``` build crashes.

**Expected/desired behavior**
Expected this guide to work.

**Comment by sebfag** [comment]
Hi,

There was an upgrade of angularfire2 last week to use version 3 of the firebase sdk. Here is the install page : [angularfire2 setup](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md)

**Comment by sebfag** [comment]
The changes are pretty straightforward but : 
1 - You have to bootstrap correctly the firebase config
`bootstrap(<MyApp>, [
  FIREBASE_PROVIDERS,
  // Initialize Firebase app  
  defaultFirebase({
    apiKey: "<your-key>",
    authDomain: "<your-project-authdomain>",
    databaseURL: "<your-database-URL>",
    storageBucket: "<your-storage-bucket>",
  })
]);`

2 - Use the right definition for firebase : 
`
In your tsconfig.json file include the following line in your "files" array:
"files": [
  "node_modules/angularfire2/firebase3.d.ts"
]`

**Comment by mgechev** [comment]
@sebfag if you have a minute, would you update the wiki?

**Comment by sebfag** [comment]
Yes it is in my mind but I won't be able before tomorrow... Hope it is not so urgent for @tarlepp

**Comment by mgechev** [comment]
Awesome! Thanks!

**Comment by tarlepp** [comment]
@sebfag no worries, just good to know that you're going to improve those docs. Thanks!

**Comment by mgechev** [comment]
@sebfag can we close this issue?

**Comment by tarlepp** [comment]
I haven't checked those wiki pages yet, so I can't be sure if those have been updated already.

**Comment by ducminhn** [comment]
Can you update the Wiki page for AngularFire2 integration? The instruction on the page doesn't work for me.

Thanks!

**Comment by AdamJo** [comment]
@ducminhn I found this wiki entry to (sorta) work [Add External Dependency](https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency). Instead of one jwt library you have to add both firebase and angularfire3 to the project.config.ts file.

Although when you run this it produces "34 semantic errors" for angularfire2 that look like this :
`angularfire2/utils/firebase_object_observable.d.ts(11,15): error TS2503: Cannot find namespace 'firebase'`

Dev will still run but the prod build is suppose to fail encase of any errors. I had to go into /tools/tasks/seed/build.js.prod.ts and comment out the following code to get it to run on prod. 

    let result = gulp.src(src)
      .pipe(plugins.plumber())
      .pipe(plugins.inlineNg2Template(INLINE_OPTIONS))
      .pipe(plugins.typescript(tsProject))
      //.once('error', function () {
      //  this.once('finish', () => process.exit(1));
      //});

You still get the errors but it should run normally on both dev/prod. 

I'd appreciate any help on how to remove the errors.

**Comment by mgechev** [comment]
Thanks for the help!

**Comment by ducminhn** [comment]
Thank you, @AdamJo
