### ISSUE TITLE
NOT an issue - Any thoughts - JSPM

### ISSUE THREAD

**Issue by Dutchboy** [mgechev/angular2-seed#1057]
Dear Minko and others!

What are your thoughts on JSPM? And to have it in this wonderful project too?

Thanks, kind regards!

**Comment by mgechev** [comment]
I've considered JSPM before a few months. It works great with SystemJS so it is quite likely to migrate the seed in near future. Lets keep the issue and the discussion open.

**Comment by Dutchboy** [comment]
I guess you've already seen it, but maybe it's worth pointing you to it?
[ng2-jspm-template](urlhttps://github.com/flaviait/ng2-jspm-template)

**Comment by karel1980** [comment]
I quite dislike jspm's idea of depending on github tags. This threatens stable builds because repositories and tags can change or even disappear without notice. Of course using github is optional, but in practice jspm itself has dependencies on versions of jspm/nodelibs-* which are available in github, but not on npmjs.
Other than that for projects where the risk of github tags moving around is acceptable, jspm does a good job.

**Comment by TheDonDope** [comment]
Just to play the role of the devil's advocate:

1. Which problem does JSPM solve, that we currently have?
2. How can JSPM improve the current state of the seed? 
3. Which breaking changes could JSPM introduce, if any?
4. Will users of the seed be affected in any way? (Say: new cli commands, possible merge conflicts)
5. Would a migration to JSPM introduce backwards incompatible changes?

Don't get me wrong: I'm all for improvement. Just the thoughts that came to my mind when reading on the issue here.

Greetings 

Dope

**Comment by Dutchboy** [comment]
@karel1980 Github tags to add versioning. You can lock them to any certain tag. I too have had a situation a tag disappeared, but that is easily solved. It is just outright perfect to be able to use github next to npm.

@TheDonDope Hi devil! :-)
1. The problem the seed project now has is that the systemJS configuration resides in numerous places. Not one single, not even two or three, and sometimes mixed. DRY. Or T-DRY. Forcing a project to have one source of systemJS "manager", from the same mastermind that systemJS maintains - I think it is a brilliant step. 
2. State - "Just do a JSPM-install and a new package is available" - ok, ok... Also a "typings-install".... And for development purposes, IDE happiness, an NPM-install.... But, back to the build/dist flow, JSPM is just perfect. SystemJS on one place.
3. In the seed, all the current code snippets implementing their own systemJS configs have to be thought over, made redundant, referring to the jspm.config.js, the jspm.browser.js etc. Added advantage?... I've read somewhere that you wanted to add seperate modules / packaged modules (shared blocks) with JSPM that will be easy.
4. Once well-documented, well-explained, then.... My bet is - less workflow code.
5. The first step being a rewrite of all the code referring to these code mentioned in point 3.

Don't get me wrong. I'm not perfect myself. I've used some of the project. I've mixed all the "good thoughts" of four projects and I'm happy with the result. 

It took me a week. Mostly because the JSPM is poorly documented. The reason being, because it actually is amazingly comprehensive or flexible. So, honestly, the question is where to start explaining? What to document about a certain option - without getting into a rewrite of documentation of external technologies. It helped me a lot to go through the source code, which is beautifully written. And well-hinted throughout.

**Comment by jerryorta-dev** [comment]
I have refactored this seed utilizing JSPM in this fork: [angular2-jspm-typescript-seed](https://github.com/UIUXEngineering/angular2-jspm-typescript-seed).

The refactor is so significant, and after seeing previous responses to JSPM requests, I think it may be preferrable to add a link to my refactored repo, rather than merge it. If that is true, then I intend to disconnect my refactored repo as a fork. I will give credit to this project and @mgechev for the environment in the README.md, as well provide a link to this project. I will then submit a PR to the list of forked repos in this project’s README.md.

At at high level, the refactor consists of:
- remove most tasks that require a tmp or dev builds. SystemJS transpiles files for dev, tests, e2e, code coverage. Only HTML dev build tasks remain due to environment variables.
- Use SystemJS for production build via [conditional loading](https://github.com/UIUXEngineering/angular2-jspm-typescript-seed/tree/master/src/client/app/shared/config).
- No scraping the files system, App variables for production and development produced by SystemJS conditional loading.
- BrowserSync has it’s own file watch feature, remove all file watch tasks. It also has
- Optimize node rimraf to use Glob instead of the walk method.

####For completeness of this dialogue, here are some notes on why I use JSPM.

To buy off on JSPM, one needs to understand the original intended goals of SystemJS proposed by @guybedford, the author of both SystemJS and JSPM. Guy researched Browserify, RequireJS, NPM, Bower, among other package managers and module loaders and set a goal to incorporate the best features of each, while improving the flaws of some. To maximize the benefits of SystemJS, JSPM becomes a powerful package mananger and systemjs configuration tool. Thus, setting up an environment maximizing these benefits requires a shift in principles and paradigm to how development environments are utilized.

In an overly simplistic and concise summary of SystemJS benefits:

For Production and Development:

- Dev is served, not built.
- Support conditional imports and loading based on production build or dev “build”.
- Never use glob patterns to scrape the file system build ( “some/parent/directory/**/*.ts” )
- Library frameworks can be loaded the same as source files ( import someModule from “someLibrary” ).
- Minimize the need for bundling of third party frameworks, especially when a framework supports ES6 standards that allows you to import a single module from a framework [Lodash ES6 Example](https://github.com/UIUXEngineering/angular1-ES6-jspm-gulp-seed/blob/master/client/app/services/factory.angularES6Class/angularES6Class.factory.js).
- Single source of truth for all App dependencies ( one SystemJS config file for the app ).
- Decouple the dev environment code from the app code including dependencies, environment variables. This is critical for enterprise teams that share features/modules, but may have different environment needs.
- Support third party ES6 frameworks that require Babel to transpile due to advanced features, while supporting TypeScript at the same time.
- Support promised based imports for special file handling ( i.e., could use this for lazy loading for non-Angular2 projects ).
- Extend SystemJS with [plugins][https://github.com/systemjs/systemjs.
- Use bundles to support Angular2 lazy loading.

For Development:

- Never have to transpile files to a temporary directory. Serve source files “as is” for development, unit-tests, code coverage ( no pre-processing files for unit tests and code coverage ).
- Minimal manual configuration of the systemjs config.

Using JSPM as a package manager supports the goals of SystemJS:

- NPM is the documented standard registry.
- Auto-update the SystemJS configs when installing a framework or module ( Improvement from Browserify, RequireJS, NPM ).
    - Update libraries similar to NPM.
    - Minimal manual configuration of SystemJS config.
- Totally modularize any feature you build along with supporting frameworks. So if you share a feature through NPM, you can “jspm install npm:@yourProject/yourFeature” and all dependencies will be installed as well -- see [example 1](https://www.npmjs.com/package/@uiuxengineering/uidk-ng-1x-translation), and [example 2](https://www.npmjs.com/package/@uiuxengineering/uidk-ng-1x-view.sample).
- Supports NPM style of automatically loading dependencies -- [see example](https://github.com/UIUXEngineering-NPM/uidk-ng-1x-translation/blob/master/package.json#L10), this expirement uses github because the NPM versions of translate has bugs.
- Use the exact same SystemJS configuration file to serve dev, unit tests, build production, and run and build code coverage.
- Provide third party SystemJS configuration overrides by using the JSPM [registry](https://github.com/jspm/registry) so I don’t have to manually configure overrides ( improvement from RequreJS and Browserify, totally optional ).
- Build app through SystemJS Builder ( via JSPM, they share the same code via modularization ).
- Like ngTemplates, process html, css/sass/scsss, json files via SystemJS plugins rather than build them with a task manager.
- Shrinkwrap all app dependencies by default. NPM improvement so much you could install two versions of the same ES6 framework, and import modules from each. Shrinkwrap is such a poor NPM feature that Google has written special [code](https://github.com/angular/angular/tree/master/tools/npm) and [instructions](https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md) to use it.

The angular-cli project creates its own version of a SystemJS configeration file builder, but it doesn't not fully embrace third party dependencies written in ES6 ( that can only be transpired by Babel ), or commonjs libraries…. yet.  The scope of angular-cli is more than a SystemJS config builder, so I may use it in tandem with JSPM. But I’d rather use the best tools for each task, and normlize commands through gulp or npm; JSPM is built specifically to support SystemJS.

**Comment by mgechev** [comment]
@jerryorta-dev good job! Sounds like a good idea, you can approach the way @NathanWalker did with the [angular2-seed-advanced](https://github.com/NathanWalker/angular2-seed-advanced).

In case we decide to switch to JSPM your fork can bring a huge value for the transition process.

**Comment by Dutchboy** [comment]
@jerryorta-dev mannnnn!!!! :-) What a concise job you did writing the above - I can't wait to check your fork!!!.... In the mean while, though, I've forked myself a working JSPM project from the original seed, which does some pretty neat tricks... Which I'm using for a live-project... It's for ionic2 too.... What I want to add still is the tree-shaking @mgechev blogged about... 

You are right about so many things, in the above, mostly the DRY, one place to put the SystemJS... jspm.browser.js :-) This file I "abuse" to let the JSPM bundle add the bundled info and then gulp-copy it (with some rename-task) into the "www" (ionic's prod dir)... 

I have mostly de-activated all the seed-project configs, because it took me too long to comprehend the reasonings behind them. Again, it wasn't DRY enough for me.

I can't wait to sniff through your project-setup!!!! THANKS A LOT!!!

**Comment by jerryorta-dev** [comment]
Thannks @Dutchboy! If you are able to share your fork as well, that would be great! There are many ideas I would like to explore, and seeing more samples is helpful.

**Comment by Dutchboy** [comment]
@jerryorta-dev I've sent you a mail - I don't know if you received it? ... Mean while, I've changed some...
... a dev-option, to serve the app files non-bundled, but with the inlineNg2Template
Mean while, I'm adding the option to "dest" it to outside the main folder, to a networked folder, which is served to the outside world, so that my close friends can shoot at it....
