### ISSUE TITLE
Deployment in production with multiple routes

### ISSUE THREAD

**Issue by JanickRoss** [mgechev/angular2-seed#1059]
Is it possible to make on your wiki an explication on How deploy a production build with multiple route on tomcat server by example ? 

As the seed minify all html files into one file, the tomcat server not able to start directly on a secondary route. 

www.example.com/secondary/ 

I suppose it's not only a seed problem but it's essential to publish a angular 2 product.

Thanks

**Comment by Sjiep** [comment]
I had the same problem last week but then with Apache. The problem is that all angular stuff should be served via the `index.html` file. In Apache can be solved using either 

- a `.htaccess` file (and making sure the apache conf file has the setting `AllowOverride all` enabled. 

- setting the [Angular 2 URL Style](https://angular.io/docs/ts/latest/guide/router.html#browser-url-styles) to hash

I used the following, see also this [SO post](http://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2): 
`.htaccess`
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```
`000-default.conf` should have the following somewhere in the file
```
<Directory "/var/www/html">
  AllowOverride All
</Directory>
```

I'm not entire sure if a similar thing exists for Tomcat.

@mgechev Would it be useful to put the above information regarding Apache in the Wiki

**Comment by mgechev** [comment]
@JanickRoss [here's how](https://stackoverflow.com/questions/13295300/making-spring-tomcat-compatible-with-html5-pushstate).

@Sjiep thanks for the comment! You should have write access to the wiki page. Do you have a few mins to share this configuration there?

**Comment by Sjiep** [comment]
@mgechev Done! See [here](https://github.com/mgechev/angular2-seed/wiki/Deploying-prod-build-to-Apache-2)

**Comment by mgechev** [comment]
Great! Thanks! :-)

**Comment by rajeev-tripathi** [comment]
Hi @mgechev and @JanickRoss - thanks for pointing this. However I have one request, I am running my app on liberty websphere server (linux enviornment). I have written a war gulp task to create war file out of my dist/prod folder. I have also set the -base-path parameter as well.
The war is getting deployed properly with the context path as my base path. It loads properly when hit some thing like this > http://myserver:myport/mycontenxt/
But for my deeper routes and page refreshes doesn't work. I have gone through your settings above and need the same sort of settings in my server.xml. Could you please provide me the same.
In nut-shell I want equivalent of below settings for server.xml
`<IfModule mod_rewrite.c>
  Options Indexes FollowSymLinks
  RewriteEngine On
  RewriteBase /mycontextpath/
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>`
