### ISSUE TITLE
Dynamic routes

### ISSUE THREAD

**Issue by jlberrocal** [mgechev/angular2-seed#1074]
Hey everybody, until now is possible to load routes in a dynamic way?

**Use case**: I need to load all the components in a folder, but i don't know how many components are there, my idea is use a json file(will be changed to a server consult) to indicate which are the components and what is the path

Is there any way for accomplish this? thanks in advance

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

The production bundle currently creates a single bundle the entire app and its dependencies. When we introduce `ngc` and tree-shaking, I don't think there's going to be a point for async routes for most applications below 30k lines of code.

**Comment by jlberrocal** [comment]
what i need is more complex than what you describe in the post, i need to read all the components from a folder and import them as routes, that's why i thought in use a json file describing where are they and which is the route that is supposed to use, but i don't have idea about how to achieve that
