### ISSUE TITLE
IDE Complaining about AppComponent directives

### ISSUE THREAD

**Issue by andreroggeri** [mgechev/angular2-seed#1078]
**Steps to reproduce**

- Checkout 2.0.0-r.3
- Install dependencies
- Open IDE (Webstorm in my case)

**Current behavior**

The IDE complains about the directives implementation (Although no error is thrown when running). If I remove the NavbarComponent and ToolbarComponent the errors goes away.

![Print](http://i.imgur.com/xzSQqYV.png?1)

**Comment by mgechev** [comment]
It is not an issue in the seed but doesn't seem like a problem in WebStorm neither. Since `NavbarComponent` and `ToolbarComponent` are not of type `Type` neither `any[]` you get this typing error.

You can workaround the issue by wrapping `NavbarComponent` and `ToolbarComponent` in an array `[NavbarComponent, ToolbarComponent]`.

On any reason WebStorm doesn't recognize `NavbarComponent` as instance of:

```ts
export interface Type extends Function {}
```
