### ISSUE TITLE
angular2-uuid.js not found (with Angular2-seed)

### ISSUE THREAD

**Issue by vega3000** [mgechev/angular2-seed#1084]
I installed angular2-uuid by typing `npm install angular2-uuid --start`.
In my code I import uuid
`import { UUID } from 'angular2-uuid';`

At this point, I have no error.
But when I write

`let uuid = UUID.UUID();`
, I have an 404 error (see below).
Did I miss something to write in my code?

Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/angular2-uuid/angular2-uuid.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by mgechev** [comment]
The main file of `angular2-uuid` is not `angular2-uuid.js` but `index.js`. You have misconfigured SystemJS.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
