### ISSUE TITLE
External css url import breaks the prod build process

### ISSUE THREAD

**Issue by salemdar** [mgechev/angular2-seed#1110]
I have noticed this problem while using `bootswatch`. Everything is fine with `build.dev` . But following lines breaks the prod build process:

```sass
$web-font-path: "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700" !default;
@import url($web-font-path);
```

Here is the error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
 Error: Broken @import declaration of "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700" - timeout

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 build.prod: `gulp build.prod --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 build.prod script 'gulp build.prod --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\workspace\bmos-admin-ui\adminui-ng2\npm-debug.log
```

**Comment by TheDonDope** [comment]
Hi @salemdar,

this is not precisely a seed problem.
The error that is thrown states the following:
> Error: Broken @import declaration of "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700" - timeout

The important bit is the `- timeout`part: The import request has a timeout (I think it is 30 seconds or something) in which it tries to resolve the the fonts through the google api. However, since you are requesting 6 different font weights all of those cannot be resolved within the timeout time. 

There are two possible solutions to this problem:

A) Retry this build. I am not kidding, i do also use google fonts in a private project and also import a few (6 in my case too) fonts. Sometimes the build does complete, sometimes it does not. But mostly, after three to four restarts it will eventually finish

B) Reduce the amount of fonts you import. Less font weights / styles to import means less time to resolve the request.

Greetings

Dope

**Comment by salemdar** [comment]
Hey @TheDonDope, 
Thanks for your reply. That also crossed my mind. 
I think I couldn't have articulated my question well enough. I actually wanted to ask how can I leave out `@import` processing. Thanks to you, I searched with `timeout` keyword included and came up with the following solution:

In the `build.html_css.ts` file, pass `processImport: false` option to the `cleanCss`:

```typescript
function processAllExternalStylesheets() {
  return merge(getExternalCssStream(), getExternalScssStream())
    .pipe(isProd ? plugins.concatCss(CSS_PROD_BUNDLE) : plugins.util.noop())
    .pipe(plugins.postcss(processors))
    .pipe(isProd ? cleanCss({processImport: false}) : plugins.util.noop())
    .pipe(gulp.dest(CSS_DEST));
}
```

**Comment by webdevinci** [comment]
Is there no way to set the timeout with cleanCss since it is a timeout error?

> `Error: Broken @import declaration of "https://fonts.googleapis.com/css?family=Source+Sans+Pro:600,400" - timeout`
