### ISSUE TITLE
dist/dev/node_modules is missing

### ISSUE THREAD

**Issue by itsmylifesoham** [mgechev/angular2-seed#1160]
Hi,

I ran npm start but my dist/dev directory does not have the node_modules and still all loads up fine. I am unable to figure out from where is it loading up the node_modules folder in the dist/dev directory which is the root of the server. 

Thanks!

**Comment by zladuric** [comment]
+1, I'd also like to know how this works. I mean, for local development, I think I've picked up somewhere in tools/utils that there's an express server behind the scenes that compiles files on the fly for dev versions. But I still wanna know more, because I don't know how to make deploy builds.

I've temporarily "solved the problem" of actual deployments by manually copying node_modules (or stripped-down version of it) to the dist/dev before deployments. (Actually I'm writing a gulp task/util for all the steps for this right now, what got me to /issues here.)

But I'd like to do it the right way, and also I'd like to know why gulp build.dev or gulp build.prod doesn't do this for me (and also how to replace some stuff, like backend urls, back there).

**Comment by mgechev** [comment]
We're using two root directories for the static development HTTP server. Here [is the config](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L429-L443) and here is [the initialization](https://github.com/mgechev/angular2-seed/blob/master/tools/utils/seed/code_change_tools.ts).
