### ISSUE TITLE
ng2 highchart failed 

### ISSUE THREAD

**Issue by devrockzz** [mgechev/angular2-seed#1224]
one.js?1471464630035:101 GET http://localhost:5555/node_modules/ng2-highcharts/ng2-highcharts.js 404 (Not Found) i got this error after npm start .

**Comment by mgechev** [comment]
You need to set proper configuration inside `project.confit.ts`.

**Comment by devrockzz** [comment]
Hi after setting project.config.ts what I will do ? Plz explain

**Comment by igorlino** [comment]
**1) in command line of your project:**

yarn add highcharts
yarn add highcharts-angular

**2) edit the /tools/project.config.ts  and extend**

 // Add packages (e.g. ng2-translate)
    const additionalPackages: ExtendPackages[] = [
{
        name: 'highcharts',
        path: 'node_modules/highcharts/highcharts.js'
      },
      {
        name: 'highcharts-angular',
        path: 'node_modules/highcharts-angular/bundles/highcharts-angular.umd.js'
      }
];

**3)  related imports in app and component modules**
follow some of the steps of the installation guide of highchart-angular so that you properly import the in your app and component modules
see  https://github.com/highcharts/highcharts-angular#installing

**4)  simple example** 
for a simple example, follow the 2 steps of
https://github.com/highcharts/highcharts-angular#hello-world-demo

**Comment by igorlino** [comment]
Note that ng2-highchars is not maintained and not official

**highchart-angular** is the **official integration** for the library.
https://github.com/highcharts/highcharts-angular
