### ISSUE TITLE
Error: Error: Type NgSelectOption is part of the declarations of 2 modules: LoginModule and InternalFormsSharedModule!

### ISSUE THREAD

**Issue by clp334264003** [mgechev/angular2-seed#1248]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by mgechev** [comment]
This error doesn't seem like an issue related to the angular2-seed itself.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
