### ISSUE TITLE
More of a ? than an issue, (how to run my node.js server file from npm start,

### ISSUE THREAD

**Issue by mthor** [mgechev/angular2-seed#1254]
I am trying to run my own node main.js file for the server, I am wondering what file do I need to change to have my node.js  server file , rn instead of the testing server that comes out of the box with angular 2 seed.

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

Also, take a look at [angular2-seed-express](https://github.com/vyakymenko/angular2-seed-express).
