### ISSUE TITLE
Missing file for proxy configuration to typings 

### ISSUE THREAD

**Issue by calazans** [mgechev/angular2-seed#1271]
Some people might run the angular2-seed behind some firewall and they need to setup the proxy configuration for npm, but typings does not use the npm proxy configuration and in this case, they have to use the **.typingsrc** file to configure the proxy for typings. 
reference: https://github.com/typings/typings/issues/106

**Comment by mgechev** [comment]
You're correct, this seems user environment specific. We may add a basic `.typingsrc` but I'd suggest to not to. In case of proxy configuration it might be even a good idea to add `.typingsrc` as entry in `.gitignore` in order to not make everyone in the team use proxy in case such is not required. What do you think?
