### ISSUE TITLE
src\client\app\main-prod.ts(5,36): error TS2307: Cannot find module './app.module.ngfactory'

### ISSUE THREAD

**Issue by renearias** [mgechev/angular2-seed#1299]
at run serve.e2e show
src\client\app\main-prod.ts(5,36): error TS2307: Cannot find module './app.module.ngfactory'.

**Comment by sasikumardr** [comment]
Since app.module.ngfactory creates at (gulp) run-time, vscode also shows same error when opening this file. 

In my opinion this module has to import at run-time. Changing main-prod.ts from

```
import AppModuleNgFactory from './app.module.ngfactory';
import { platformBrowser } from '@angular/platform-browser';

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

to 

```
import { platformBrowser } from '@angular/platform-browser';

let ngFactory = require('./app.module.ngfactory');
let AppModuleNgFactory = ngFactory.AppModuleNgFactory;

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```
will resolve tslint issue in vscode. May be your issue too. I actually could not reproduce your issue.
