### ISSUE TITLE
Update RC.6 to  Final Release

### ISSUE THREAD

**Issue by canygt27** [mgechev/angular2-seed#1384]
How can I update my project folder to version of final release?

Have a nice day.

**Comment by apocarteres** [comment]
1. pull latest changes
2. merge conflicts between your codebase and actual one
3. in case of any trouble - read change log and goto step 2

i have been using ```angular2-seed``` for a while and every time i update to next revision i follow that simple formula and it works fine.

**Comment by canygt27** [comment]
I have upgraded thanks for this but my build.prod is not working. 

When I write  `npm run-scirpt build.prod --scss` , it is staying like on the image and not going.

![screen shot 2016-09-27 at 16 30 25](https://cloud.githubusercontent.com/assets/13340329/18875776/da785de0-84cf-11e6-844d-f894ebf51070.png)

**Comment by apocarteres** [comment]
@canygt27 you probably did something wrong during update. 

Btw why do you use 
```
npm run-scirpt build.prod --scss
```

instead of 
```
npm run build.prod --scss
```

i just tried to build prod with ```scss``` and it looks fine

Did you try to do the same of fresh ```angular2-seed``` checkout?

<img width="225" alt="screen shot 2016-09-27 at 4 35 36 pm" src="https://cloud.githubusercontent.com/assets/3305624/18876348/fd92db14-84d1-11e6-9c8d-201dcc2f9efe.png">

**Comment by canygt27** [comment]
There is an issue like this on my terminal.

![screen shot 2016-09-27 at 18 45 30](https://cloud.githubusercontent.com/assets/13340329/18881063/af6ad728-84e2-11e6-9fa9-63cf8eb841f8.png)
