### ISSUE TITLE
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode. http://localhost:5555/assets/data.json Failed to load resource: the server responded with a status of 404 (Not Found) name-list.service.ts:38404 - Not Found

### ISSUE THREAD

**Issue by clp334264003** [mgechev/angular2-seed#1388]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
http://localhost:5555/assets/data.json Failed to load resource: the server responded with a status of 404 (Not Found)
name-list.service.ts:38404 - Not Found

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by mgechev** [comment]
Yes, when running the seed in dev, it is supposed to show the warning that you're running it in development mode.

Most likely the problem that you're experienced is environment specific, because `assets/data.json` exists. Please take a look at the wiki in order to get more complete understanding of how the seed works. Also I'd recommend you to go through the files in `tools` and read the comments in there.
