### ISSUE TITLE
Question: what does 'Supports multiple Angular applications with shared codebase in a single instance of the seed.' mean?

### ISSUE THREAD

**Issue by mikemichaelis** [mgechev/angular2-seed#1407]
Supports multiple Angular applications with shared codebase in a single instance of the seed.

Does this mean the seed may itself contain multiple applications?

**Comment by mgechev** [comment]
I think it is possible. We did some experiments in the past. Here's some research by @mko https://github.com/mgechev/angular2-seed/issues/1157.

Also, you can take a look at https://github.com/NathanWalker/angular2-seed-advanced.

**Comment by mko** [comment]
@mikemichaelis I've actively got code in production for separate applications using a file structure similar to the following:

```
src/
    app1/
    app2/
    app3/
```

The biggest thing of note was that I had to create custom tasks that compiled and watched those apps separately in the `gulp` workflow using completely separate `tsproject` instances because of the `gulp-typescript` error referenced in #1157. I've just recently updated to the version of `gulp-typescript` that doesn't have the `empty.ts` error, but I haven't tried refactored to a single `tsproject` yet to see if it's truly fixed.

**Comment by mikemichaelis** [comment]
Thanks guys!  I appreciate the quick response!
