### ISSUE TITLE
tsconfig.json in src breaks IDEs such as VSCode

### ISSUE THREAD

**Issue by dlabaj** [mgechev/angular2-seed#1419]
Noticed that the tsconfig.json in src causes issues with some IDEs such as Visual Studio Code.  Can this be removed and only one tsconfig.json be located at the root folder?

**Steps to reproduce and a minimal demo of the problem**

Clone the repository, and perform an npm install.  After that open an IDE such as VSCode.  When navigating to the source code in the IDE you will see errors for calls such as **define, it, etc.**  for testing.  The are causing the IDE to report  "Can not find name 'describe' [] any".  If you open app.component.ts you will see "[ts] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.", even though this is set in the tsconfig.json file.  Removing the tsconfig.json file from src will fix the IDE, however the build scripts in tool will no longer work.

**Comment by mgechev** [comment]
@dlabaj we cannot remove any of the `tsconfig.json` files because the one in the root is used by `tools` and the one inside `src` is used by the app. Take a look at this issue to see how you can handle the issues you have https://github.com/mgechev/angular2-seed/issues/719.

**Comment by karlhaas** [comment]
@mgechev I' having a problem with the tsconfig.json in the root folder and AoT compilation. Because the file is copied to tmp/app, the relative paths don't work anymore.

e.g. we have the following paths configured:
```
    "baseUrl": "./src/client",
    "paths": {
      "shared/*": [
        "app/shared/*"
      ],
      "core/*": [
        "app/core/*"
      ]
    }
```

If we copy the file into the app folder, then app/shared/* is not valid anymore.

I think that the tsconfig.json in the root folder is just used for the experimental aot build because for build.js.prod and build.js.dev the one in src/client is used. Am I right?

Why do we have to copy the tsconfig.json file into the app folder and not in the tmp folder?

**Comment by mgechev** [comment]
The root tsconfig.json is used implicitly by ts-node. The task `compile.ahead` uses tsconfig from `app`. An alternative solution is to add another entry for tsconfig in `seed.config.ts` but I think this will make the file far too busy.
