### ISSUE TITLE
Karma does not load rxjs

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#183]
Fix path to `@reactivex/rxjs/*`

**Comment by jesperronn** [comment]
:+1:  for adding the dependency explicitly. The reason why this was a problem to you and not to Travis is due to Travis using Npm 2, and you probably using npm 3 locally.

Npm 3 'flattens' dependencies, so that @reactivejs is not found under `node_modules/angular2/node_modules/@reactivejs`

This happened for me, too. Adding the depencency explicitly is a great idea, thanks.

One question: Can you think of any issues using `rxjs@5.0.0-alpha.6`, when Angular2@alpha44 is using  `rxjs@5.0.0-alpha.4`??
