### ISSUE TITLE
Keep tsd definitions inside the repo ?

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#184]
I see a couple of advantages to do so:

* No more error with Travis (or less at least)
* Already referenced `./tools/typings/tsd/**/*.d.ts` in `tsconfig.json` files
  * right now if we just clone, install, start ... tsd definition are missing in tsconfig

**Comment by tarlepp** [comment]
Travis is failing because of GitHub rate limit, which can be easily solved as described in #176 

If the point is keep this repo as barebone as possible, then I wouldn't include these typings. And imho it's good that repo contains only things that *we* have coded, not 3rd party libraries.

But generally I think there is no "wrong" or "right" answer for this.

**Comment by ludohenin** [comment]
My main concern here is 

> right now if we just clone, install, start ... tsd definition are missing in tsconfig

**Comment by sclausen** [comment]
@ludohenin The problem that the typings are missing in `tsconfig.js` could be solved with adding the following:
``` json
{
    "filesGlob": [
        "!./tools/typings/tsd/**/*.d.ts"
    ]
}
```
I don't know how other IDE's treat the `tsconfig.json`, but atom-typescript doesn't mark e.g. any express imports as errors (`tools/utils/server.ts`) If I exclude tsd-typings in filesGlob. Would this be a valid solution for one of your arguments?

IMHO including the tsd typings in git is really dirty project design. It adds unnecessary files to the repository, because their versions are already defined in `tsd.json`. One wouldn't include node_modules, or bower_components either.
I think doing this just because of the git rate limit and travis is not worth the cons.
