### ISSUE TITLE
Unit/E2E Tests?

### ISSUE THREAD

**Issue by jgodi** [mgechev/angular2-seed#25]
Is there any plan to add Unit/E2E tests to this? With/without code coverage?

**Comment by ludohenin** [comment]
@jgodi Not quite sure yet. Probably not. This will most likely be left to showcasing - [AngularShowcase](https://github.com/AngularShowcase)

**Comment by NathanWalker** [comment]
Thank you for this repo! It is very helpful as a starting base. I would vote that adding Unit/E2E test setups for this repo would be excellent. If I knew how, I would certainly provide a PR with it for this.

+1 to adding test setups to this repo.

**Comment by mgechev** [comment]
We discussed adding tests. However, we need to agree upon given testing framework.

Since we are trying to keep the project with as less dependencies as possible and to not force our preferred technologies, we didn't add any configuration yet.

However, if it is a common feature request we might consider adding tests.

**Comment by radotzki** [comment]
I agree with @NathanWalker.
Tests are core of the project, especially when the api change every new release.

+2

**Comment by NathanWalker** [comment]
It looks like @ludohenin has some progress on this branch:
https://github.com/mgechev/angular2-seed/tree/test

I assume it will eventually be merged in. Awesome.

**Comment by ludohenin** [comment]
Yep. Still have some issues loading templates. I've had to inline them for the test to work.

**Comment by thekennysong** [comment]
+1
