### ISSUE TITLE
In OSX Firefox it now takes about 3 seconds before the project is loaded locally

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#265]
Something is wrong with app loading in OSX Firefox now. My application that is built on angular2-seed sticks on "loading.." and when I click around, switch browser tabs, open/close browser console it sometimes completes loading and shows the content. Original angular2-seed project is taking about 3 seconds to remove "loading.." and show home page.

**Comment by ludohenin** [comment]
@tandu are you using it on your local machine ?

**Comment by tandu** [comment]
Yes.

**Comment by mgechev** [comment]
@tandu currently we load all the modules from Angular 2 (including the internal modules, the router, http etc) on demand, which slows down the initial load.

This is due to the fact that we require Angular 2 by using:

```ts
import {whatever...} from 'angular2/angular2';
```

Which goes to `node_modules` and loads all the angular files one by one.

This is caused by the change we made in https://github.com/mgechev/angular2-seed/pull/262. 

## Possible optimizations

1. As possible optimization we can provide the bundles for the core libraries of the seed (such angular 2 and all the standard modules such as router & http), like we did before.
2. Bundle all the files with the systemjs or browserify (it doesn't make big difference which one we're going to use for the dev build as soon as we're generating source maps).

**Comment by mgechev** [comment]
I implemented the first strategy since with the second one would take too much to create the entire bundle.
