### ISSUE TITLE
npm test fails on Ubuntu 15.10

### ISSUE THREAD

**Issue by sclausen** [mgechev/angular2-seed#314]
Running test on my Ubuntu 15.10 fails with the error:
```
START:
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS2
INFO [launcher]: Starting browser Chrome
ERROR [launcher]: Cannot start PhantomJS2
	
INFO [launcher]: Trying to start PhantomJS2 again (1/2).
ERROR [launcher]: Cannot start PhantomJS2
	
INFO [launcher]: Trying to start PhantomJS2 again (2/2).
ERROR [launcher]: Cannot start PhantomJS2
	
ERROR [launcher]: PhantomJS2 failed 2 times (cannot start). Giving up.
```
Unfortunately, no additional info why PhantomJS2 can't be started was given :disappointed:
If you encounter this problem, you should execute `node_modules/phantomjs2-ext/bin/phantomjs` directly and see which lib is still missing.
With Ubuntu 15.10, my system missed `libicu52`. Older Ubuntu versions do have this lib in their repositories, but as of 15.10 one has to load it e.g. from here http://packages.ubuntu.com/trusty/amd64/libicu52/download
A friend of mine with arch-linux also missed `libpng12`, so, if you encounter this problem, run phantomjs directly and see whats missing.

**Comment by ludohenin** [comment]
Why do we need PhantomJS ?

**Comment by sclausen** [comment]
@ludohenin I don't now enough about phantomjs2, but in general, phantomjs is useful, for running tests on build servers without a firefox, or chrome installed.

**Comment by corvinusy** [comment]
By default 'npm test' starts with project-local phantomjs (located at ./node_modules/phantomjs2-ext/lib/phantom/bin/). This binary on my machine quits with error: './phantomjs: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory'.

I just replaced it with link to my global source-builded phantomjs and tests ran OK.

P.S. npm-installed binary on linux is 1.9.x due to current phantomjs issues.
