### ISSUE TITLE
Use bower for frontend libraries 

### ISSUE THREAD

**Issue by lihaibh** [mgechev/angular2-seed#315]
There should be seperation between backend libraries and frontend libraries. 
All the libraries for the tools and server should be installed by npm while frontend libraries like angular and bootstrap should be installed by bower. 

Also we should run the server from dist/env and not like today we run it from root only because we need access to node packages folder

**Comment by mgechev** [comment]
Last a couple of months most of the JavaScript libraries (including front-end and back-end) have moved to npm. The flat structure of bower has a lot of drawbacks. I don't think it is necessary to include one more package manager in the picture.

**Comment by ashblue** [comment]
Could this be re-opened? Our team needs bower package management for various reasons. Bower is pretty popular and used by quite a few dev teams.

**Comment by mgechev** [comment]
In case you need bower, you can add support to the seed in your custom clone by going through the following two steps:

- Update `browser-sync` plugin config in `project.config.ts` by providing `bower_components` in the `routes` section.
- Update the SystemJS config to `use bower_components` instead of `node_modules`.

**Comment by ashblue** [comment]
Fantastic, was wondering if there was a way to reroute the pipeline.
