### ISSUE TITLE
Should build.prod concatenate files in lib into libs.js?

### ISSUE THREAD

**Issue by sondreb** [mgechev/angular2-seed#327]
How come the gulp task build.prod does not concatenate all the files in the lib folder into a single file? Have there been done any performance verification that it is actually faster and better with 9 individual files?

If there have been no tests and no conscious decision on not bundling those files, is this something you could consider adding to the production output?

Perhaps two outputs, shims.js and libs.js, so they can be included before and after the System.config execution.

**Comment by mgechev** [comment]
Yes, it should. There was a problem with the minified version of systemjs. @ludohenin can explain the issue further since he is involved with the production build.

Although concatenating the files is an important task, there is still work pending on Angular 2 as well which will reduce the bundle size (such as API for templete precompillation) so optimizing the production build wasn't top priority for us.

After the holidays we will work on this task for sure :-)
