### ISSUE TITLE
Use components relative assets paths

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#351]
`gulp-inline-ng2-template#0.0.10` brings support for relative assets path. Do you think we should use this feature? It would also mean that assets will have to be inlined even for `dev`.

**Comment by mgechev** [comment]
Inlining the templates will not allow hot loading since we won't be able to associate (out of the box) the changed template with its corresponding component.

I'm also against inlining templates for dev because of the unnecessary magic that happens. As user of the seed I'm working with external templates but once I make a change the templates and styles are automagically getting inlined.

**Comment by mgechev** [comment]
Can we close this issue?

**Comment by Bigous** [comment]
I think that we should not inline things (at least not as a default behavior). I think it will be necessary to have lazy component load... for really big applications and it can be a pain to have if everything is inline... but this is another discussion.
