### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by BostjanPisler** [mgechev/angular2-seed#392]
I get this error in chrome console when I add angular2-jwt to the project. 
Same problem in the sails example also.

**Comment by BostjanPisler** [comment]
Ok now it's gone and the app works, but I'm getting 1600 lines of "Duplicate identifier ..." in iTerm.

**Comment by mgechev** [comment]
You just need to:

```bash
npm install angular2-jwt --save
```
And inside, for instance, `about.ts` use:

```ts
import * as jwt from 'angular2-jwt/angular2-jwt';
// ...
console.log(jwt.AuthConfig);
```

**Comment by mgechev** [comment]
You get the typing errors because `angular2-jwt` depends on angular2 beta.0. The seed project on the other hand uses angular2 beta.1 (the latest version). Because of the flat structure of npm 3.x.x we get:

   * angular2 (beta.1)
   * angular2-jwt
      * node_modules
         * angular2 (beta.0)

Both angular2 packages include the typing definitions required by Angular 2 so thats why you get:

```
/node_modules/angular2/typings/selenium-webdriver/selenium-webdriver.d.ts(4254,11): error TS2300: Duplicate identifier 'WebElement'.
```
In order to fix this issue you can:
- Make the angular2-jwt team update to the latest beta
- Switch the seed project back to angular2 beta.0:
   - By using the `2.0.0-beta.0` tag (`git checkout tags/2.0.0-beta.0`)
   - By changing the `package.json` angular2 version (better since you'll take advantage of the latest prod build).

**Comment by BostjanPisler** [comment]
Awesome, both solutions worked.

For 2nd one I forked and PR'd with updated dependency. Also temporarily ran:
`npm install github:BostjanPisler/angular2-jwt --save`

Thank you for the help and for the great repo, perfect setup IMO.
