### ISSUE TITLE
How to reduce the size of prod lib.js, which is ~1M?

### ISSUE THREAD

**Issue by flyingmutant** [mgechev/angular2-seed#44]
Is this possible or not, and what have caused such a huge size (compared to ~150kb for Angular1)?

**Comment by mgechev** [comment]
I took a brief look at the bundle. It seems that we have Angular 2 twice there. One of the copies comes from the router.

If can change the build and make TypeScript transpile the modules to CommonJS, so that later we can bundle them with browserify. I believe, after this we can remove:
- traceur.js
- system.js
- all associated to them sourcemaps

Not sure about the last suggestion but its worth trying. I'll create two additional tasks based on my comment.
