### ISSUE TITLE
Really long buildtime

### ISSUE THREAD

**Issue by apavillet** [mgechev/angular2-seed#496]
Hi all,

Maybe I'm doing something wrong but the dev build takes an awful long time on my computer ( mac book pro, should not be an issue)

`[14:11:16] Finished 'clean.dist' after 99 ms
[14:11:16] Starting 'tslint'...
[14:11:19] Finished 'tslint' after 2.7 s
[14:11:19] Starting 'build.sass.dev'...
[14:11:19] Finished 'build.sass.dev' after 171 ms
[14:11:19] Starting 'build.assets.dev'...
[14:11:20] Finished 'build.assets.dev' after 1.03 s
[14:11:20] Starting 'build.js.dev'...
[14:11:41] Finished 'build.js.dev' after 21 s
[14:11:41] Starting 'build.index.dev'...
`

As you can see, build.js.dev takes 21s

 Am I missing something or should I add / remove a library ?
Thanks

**Comment by Bigous** [comment]
No, it takes about 18s on my machine too, but it's not a pain to me, because I use it in the folowing form:
1. Use ```npm start``` in a separated terminal - it will build and start BrowserSync with your application, monitoring the changes in your code and refreshing in about no time.
- Code
- Test
- Code
- Test

So, the 20s build does not affect my workflow.

**Comment by mgechev** [comment]
@apavillet there are a couple of slowdowns:

- [x] The gulp is using static typing, which means that everything goes through compilation. We've optimized it already by using lazy tasks loading
- [x] Transpilation of the application's source code. We are using incremental transpilation so we've optimized everything we can.

The time required for running the tasks for first time could be optimized with a second or two more since we load a few tasks twice but the change won't be significant.

**Comment by apavillet** [comment]
Ok thanks for the answers :)

**Comment by brian428** [comment]
I don't know enough about how the TS incremental compile works, but the build time doesn't seem to be any different between an initial build (npm start) and a watched change to one file. So during npm start, the build.js.dev task might take 6 seconds. But after a change to one TS file, build.js.dev might take 5.8 seconds. Basically, it seems like build.js.dev always takes the same amount of time. Is it possible that incremental compilation isn't actually happening the way it's expected to?

**Comment by d3viant0ne** [comment]
@brian428 
- Initial build takes 6.73s (Mid-2014 MBP on NodeJS 5.6.0)
- Any change made within the project build.dev executes in ~2.5s

So I hate to throw out "Works on my machine" but that's the way it's looking :)

Curious, what node version are you running?

**Comment by brian428** [comment]
Hmm. I'm on Node 4.2.5 and NPM 3.7.5. That said, I wouldn't *think* that the Node version would really matter, right? It seems more like the "incremental" compile is actually just recompiling everything each time. Tomorrow I'll try doing a compare with the latest in Git to make sure my project isn't missing some change that would affect this (but I believe I've kept things up to date). If that doesn't bear fruit, maybe I'll try upgrading Node to 5.x just to see if that has an effect.

**Comment by d3viant0ne** [comment]
@brian428 I've found that things are generally faster in Node 5.x which kind of blows as I'm not big on using non-lts offerings.

That said, it was enough to get me to move from node 4 LTS over to 5.x
