### ISSUE TITLE
Feature: More complex components / routing

### ISSUE THREAD

**Issue by d3viant0ne** [mgechev/angular2-seed#515]
I have fielded quite a few questions based on mis-configuration of new components, in particular sub-components / child routes /  custom router outlet.

- [ ] Add a component or two a bit more "real world"
- [ ] Tests around more complex components to catch more bugs before then end up in extended forks
- [ ] Expand documentation in the wiki based on example 

@mgechev @ludohenin Thoughts?

**Comment by mgechev** [comment]
@nareshbhatia had suggestion about improvements in the component's styles and the entire UI in general.

We can merge your suggestions with his in order to achieve some great results and keep the seed minimalistic and simple in the same time.

**Comment by ludohenin** [comment]
I second @mgechev

**Comment by d3viant0ne** [comment]
Cool. @nareshbhatia rattle off a list of what you are proposing and we can get it spec'd out and get to work.

My thinking was this will go hand in hand with #506 where we eventually consume the proposed angular2-seed-tools package and provide a more robust application highlighting it's API's and overrides.

**Comment by nareshbhatia** [comment]
Depends on what we are trying to achieve. I had originally suggested something very simple for giving a more polished look:

1. A prominent navbar at the top.
2. Proper margins around the content area. Currently content is hitting the left margin.
3. Replace the smiley icon with something more useful, e.g. a menu icon in the navbar.
4. Make navbar a component instead of hardcoding in `app.html`. So `app.html` would look simply like this:

```
    <section class="sample-app-content">
      <navbar></navbar>
      <router-outlet></router-outlet>
    </section>
```

![angular2 seed screen shot](https://cloud.githubusercontent.com/assets/1220198/13028435/fb37f784-d23c-11e5-8220-67ab4885ce0b.png)

I think what @d3viant0ne is suggesting though is a bit more ambitious, i.e. a more complex example that will not only shake out unknown issues but also be our *reference app* for how to use angular2-seed. One thought is to rewrite the [personal finance app](https://github.com/archfirst/manage-my-money-client) that I wrote for my Angular 1 template. It is not as simple as a single-screen to-do app, but not overly complex either. It exercises routing, master/detail screens, embedding D3 in Angular components etc. It also hits a real Node.js back-end and hence demonstrates working with real RESTful services (of course, we can fake it to make the app standalone).

This approach may work nicely with our *separate out the tools* thinking. Now the app itself could be our reference for the [angular2-style-guide](https://github.com/mgechev/angular2-style-guide).

As a side-note, I would be reluctant to build something like this on top of raw CSS. We should at least use a preprocessor (if not a component library). All depends on how strict we want to be about introducing dependencies.

Thoughts?

**Comment by koodikindral** [comment]
@nareshbhatia - I'ts actually pretty good idea to have header & footer as a separate components, I've implemented things in a similar way in my application  (Y)
The only problem which I was facing was difficulty to share state between the components - for example, I wanted to reload some content from a REST API, when user changes the language in navbar in a component, which was inside the router-outlet.

**Comment by d3viant0ne** [comment]
@nareshbhatia - Well, lets start at the top with technologies.

I'm flexable
- ng2-bootstrap or / material / whatever
- css / sass / post-css / whatever

Now to my "vision" for lack of a less CEO(ish) word. I have been on some soft of screen share with 4 different people in the last 3 days, all having issue with the seed once they extend it. All the problems fit into two different buckets.

1.) Incomplete / Incorrect merge of upstream changes resulting in something breaking. This we are hoping to solve with #506 
2.) systemjs / import issues when trying to add new and/or more complex components. I can tell you from first hand knowledge, people have extended this seed project a really long way.

The other outliers we actual bugs in either our project or an issue with a runtime dependency.

Working off the assumption that we go with @ludohenin 's suggestion in #506 and turn the tools into an npm package with APIs that can be overridden in the applications config what I am proposing is we look at real life use cases and build the app to cover / test / document them in their simplest form.

Along with that, it was suggested & I agree that it couldn't hurt to pretty things up a bit. That said, I think we should be more concerned with components, routing, extending use cases / test coverage / docs. 

If we start adding tons of design related code to the example project, people may end up getting lost in it and missing the point of the project. Not to mention, they will most likely have to rip all of it out when building their own. I'm betting people still base off of the application as opposed to using it as a functioning guild to working with the tools api.

**Comment by d3viant0ne** [comment]
@nareshbhatia Exactly. 

1. Build out some real world(ish) use cases and add them
2. Get the tools packaged
3. Modify app to use the APIs in the tool
4. Pretty it up
5. Win @ the internets :)

We can extend it later or build features in forks later if we so chose. I'm just looking to try and address peoples pain points. 

The seed project has become the base of more beta applications than I would have thought to be honest. It's on us to try and make the continued maintenance as painless as possible.

I'm open to any suggestions that helps to facilitate that.

**Comment by nareshbhatia** [comment]
@d3viant0ne, the more I think about it, I am coming to a conclusion that angular2-seed is not the place to create complex use cases. The goodness of this projects is in the tools and we should leave the app part dead simple - perhaps beautify it a bit and make sure it conforms to guidelines (#486 & #490), but that's it. This will allow us to move the seed project itself in the direction of tools, as discussed in #506, and not even break it into a separate project.

I propose that we all contribute various sample projects to demonstrate complex use cases, report any issues that we find and get them fixed in the seed project.

How does that sound?

**Comment by ludohenin** [comment]
@nareshbhatia that sounds perfect ... that's actually always been the goal.

**Comment by mgechev** [comment]
@nareshbhatia, @ludohenin agree.

**Comment by d3viant0ne** [comment]
@nareshbhatia - Accomplishes the same goal, that works for me.

**Comment by d3viant0ne** [comment]
@nareshbhatia @mgechev @ludohenin - That would make the overall plan ...

- package angular2-seed-tools
- Modify angular2-seed to use npm packaged tooling & maintain level of application complexity
- Then get Minko to create an angular2-advanced-seed project and expand the use cases there

More of less ?
