### ISSUE TITLE
Include reference to Http

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#62]
Since using the `http` module is quite often case, I'm opening this issue for a discussion on whether you think we should add the module to the seed by default.

**Comment by tarlepp** [comment]
I think that is a good idea, because ```http``` is most likely to used.

**Comment by NathanWalker** [comment]
I also agree. I know some people still prefer `fetch` but I think it would be best practice to use `Http` module from Angular2 and it is a standard (somewhat core) module that most applications need.

+1

**Comment by aboeglin** [comment]
I would say it depends, since http now will work on its own and won't depend on angular2 anymore, anything could be used really. Since I started to work on the source and destination folders for the build, I thought maybe we can expend our configuration, put it all in a separate file that would handle configuration stuff in json format. And then we could have a boolean property to activate it or not.

Say :
```
var Configuration = {
  srcFolder: 'app',
  destFolder: 'dist',
  modules: {
    http: true,
    router: true
  },
  ...
}
```

In the end it's the same case for the router. Most apps will need routing, most apps will need http to call apis. By default we could then say deactivate http and activate router ( which we'd need at the moment anyways to support the sample app ). And document the use of the configuration file. So people wouldn't need to mess with the gulpfile at all anymore.

Anyways, people would still need to handle extra dependencies themselves though. Even though for that we could somehow manage to list it somewhere in the configuration file too.

**Comment by mgechev** [comment]
Looks good to me. Thanks for the PR!

**Comment by ludohenin** [comment]
I don't think we should.
One of the goal is to have the seed very generic and adding module like `http` is very straight forward.

**Comment by mgechev** [comment]
I agree on the purpose of the seed. If we add the module we do not have to provide examples of its usage, we can only add it to the build process in order to allow developers to include it only by adding a reference to it. We can eventually add a comment inside `app.ts` or `init.ts` stating its identifier, something like:

```
// import {Http, httpInjectables} from 'http/http';
```
What do you think for this compromise option?

**Comment by ludohenin** [comment]
Maybe we can do something like that.

**Comment by mgechev** [comment]
Alright, we can plan it for alpha36 then.

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/commit/ddad9af6cc4bfc1d8efa35e5e46b50d5aafba60a
