### ISSUE TITLE
Create library for angular2 with angular2-seed

### ISSUE THREAD

**Issue by enricosecondulfo** [mgechev/angular2-seed#686]
Hello guys,
i'm a lover of angular2-seed and i would like create a library with this. How could i do?
Thanks for your work.

**Comment by mgechev** [comment]
Hey @enricosecondulfo!

You can create demo of the library using the content of the `app` directory. The library itself could be placed somewhere inside `src` as well, for instance `src/lib`. After that all you need to do is to update `package.json` to point to the library's typings + main file, and set the correct dependencies. I'd recommend you to set `angular2` as a peer dependency.

Once you configure that create an `.npmignore` file and export only `dist/dev/lib/*` or wherever the dev build has put your library after transpilation.

In the `.npmignore` you should add at least `tools` since it is not necessary for the users of your library to download these scripts.

**Comment by enricosecondulfo** [comment]
Thanks for your quick response and thanks again for yours work.
