### ISSUE TITLE
NPM install failing

### ISSUE THREAD

**Issue by aderito7** [mgechev/angular2-seed#715]
I have to run `npm install` a few times before the process completes successfully. It always fails at `typings install && gulp check.versions && npm prune` with `typings ERR! message Unable to readyings typings for "X"...`. It's not always the same module.

**Comment by mgechev** [comment]
You can try to install the typings first using `typings install`. After that, once all typings are available you can try running `npm install`. Let us know if this helps somehow.

**Comment by aderito7** [comment]
@mgechev Neither approach works. I guess the problem could with the typings module itself. I've tried to three typings@0.7.12, typings@0.7.11 and typings @0.7.9 with the same result.

**Comment by d3viant0ne** [comment]
@aderito7 - You get that error when bleeding typings into a global scope.

Check your tsconfig.json & ensure it's up to date with seed#master

Specifically, you should not have a glob anywhere in here
https://github.com/mgechev/angular2-seed/blob/master/tsconfig.json#L19-L24

**Comment by aderito7** [comment]
@d3viant0ne I have run this process from scratch from the README.MD and run `git clone` as is on the file. Immediately thereafter I run npm install. Perhaps I'm the only one having this problem and there is an issue on my side? I would then certainly have to relook stuff here. Or move this issue to https://github.com/typings/typings/issues as they seem to be the culprit. Either way I think it affects anular 2 seed as well.

**Comment by d3viant0ne** [comment]
If you are running a fresh checkout of the seed - I have no idea what the issue is as it works just fine on #master. In which case, I would ask what node version you are running.

Also, check the output of "npm list -g --depth=0" and ensure you don't have something installed globally that is conflicting.

If you are running a private fork or copy of the seed ( which it appears you are ) - You are most likely out of sync with #master as the problem you are describing doesn't exist in this repo.

The only time I have ever seen it happen is when I updated ts-node in a PR and had to change the "exclude" in the tsconfig.json and remove the glob pattern in this PR - https://github.com/mgechev/angular2-seed/pull/661/files.

**Comment by aderito7** [comment]
After running `npm install` a few times the project finally installed normally. However, I was using angular2-seed on a brand new laptop, having already started on my older one. This issue happened when I started out as well, but it would only happen once and all I'd had to do was just run `npm install` again and all was fine. FYI, this is my output for running `npm list -g --depth=0`. Perhaps it's usable. Shall I close this?

├── bower@1.7.7
├── cordova@6.0.0
├── electron-prebuilt@0.37.2
├── gulp-cli@1.2.1
├── jspm@0.16.31
├── live-server@0.9.2
├── rimraf@2.5.2
├── ts-node@0.6.2
├── typings@0.7.9
└── vs-tac@1.0.16

**Comment by d3viant0ne** [comment]
Remove ts-node & typings globals

**Comment by aderito7** [comment]
Thanks, I missed that change in the docs
