### ISSUE TITLE
Failing to load config variable

### ISSUE THREAD

**Issue by ShurikAg** [mgechev/angular2-seed#743]
Hi all, 

I am trying to read config variable from that I defined in project config but browser complains about mot finding the config file.
In the project.config.ts :
```
export class ProjectConfig extends SeedConfig {
  BACKEND_BASE_URL = argv['backend_base_url'] || 'http://localhost:8080';
```

And in one of my service classes I have:
```
import {BACKEND_BASE_URL} from '../../../tools/config';  // Yes, it is a valid pass
...
return this.http.post(BACKEND_BASE_URL + '/api/login', body, options).toPromise()
...
```

The browser tries to pull it as ```http://localhost:3000/tools/config.js``` and of course failing with 404.
Is it even supported?

**Comment by mgechev** [comment]
`project.config.ts` is only for tooling configuration.

You need to define this constant inside of the `src` directory in order to make it accessible by the rest of the app:

```ts
// src/config.ts
export constant BACKEND_BASE_URL = '<%= BACKEND_BASE_URL %>';
```

This way the value of the constant `BACKEND_BASE_URL`, which is defined in `project.config.ts` will be interpolated within the rest of the code inside `src/config.ts`.

**Comment by ShurikAg** [comment]
Thank you, Sir!
