### ISSUE TITLE
Production Build wrong paths - Windows 10

### ISSUE THREAD

**Issue by JMSantos94** [mgechev/angular2-seed#755]
Hello Guys, I have been trying to make a production build.
However, when I try to run it after it has been built, the browser cannot load the necessary node_modules and files necessary.

OS: Windows 10
Node version: 5.10.1
npm version: 3.8.3
Browsers: chrome 50.0.2661.75 m, firefox 45.0.2

After running `npm run build.dev` there are no errors, but when I try to open the production build, it tells me that files are missing.

![angular2-cli](https://cloud.githubusercontent.com/assets/10554515/14512368/5dd7049a-0193-11e6-8cb4-c22a5d5efd7a.PNG)

Here is a screenshot of the console errors:

![angular2-errors](https://cloud.githubusercontent.com/assets/10554515/14512406/9d5d0f74-0193-11e6-9e69-f936f3eef697.PNG)

What I can see is that after I run the production build, it changes the paths of all the files to wrong ones. The absolute path looks for node_modules on C:\\ which I find kind of odd.

Anyone facing a similar issue on windows ?

**Comment by mgechev** [comment]
@JMSantos94 is it from a fresh clone or you did changes?

**Comment by d3viant0ne** [comment]
@mgechev - I'll spin up a windows vm and try it on a fresh clone of the seed.

**Comment by JMSantos94** [comment]
@mgechev I made a few changes. More specifically, I added a couple of components but I didn't mess with any configuration file. I will try to make a fresh clone and share with you guys the result.

**Comment by mgechev** [comment]
@JMSantos94 awesome! Looking forward for the results!

**Comment by JMSantos94** [comment]
@mgechev I just built a fresh clone, and I got the same errors.

Here is my output from the build.dev:
![angular2-cli-dev](https://cloud.githubusercontent.com/assets/10554515/14535282/f737aff2-0221-11e6-8980-b2bb245f8e1c.PNG)

Same with a production build
![angular2-cli-prod](https://cloud.githubusercontent.com/assets/10554515/14535348/4bd6412c-0222-11e6-91ca-165540c2675d.PNG)

Console from build.dev:
![angular2-errors-cleanbuild](https://cloud.githubusercontent.com/assets/10554515/14535465/d7edc8e2-0222-11e6-9e54-f71d7332553f.PNG)

Console from build.prod:
![angular2-errors-prod](https://cloud.githubusercontent.com/assets/10554515/14535479/eb0257d6-0222-11e6-94a8-a6685ded7a4d.PNG)

It seems the issue is the paths, for example the relative path ./css/all.css?1460650832631 is correct, but for some reasons it is read as an absolute path to C:/

Hope this helps, if I find any solution, I will make sure to post it here =)

**Comment by JMSantos94** [comment]
@mgechev I manually solved it by modifying the index.html file.

If anyone is facing the same issue. Delete this line: `<base href="/">`

And modify the following three lines:
```
<link rel="stylesheet" href="/css/all.css?1460650832631">
<script src="/js/shims.js?1460650832626"></script>
<script src="/js/app.js?1460650832628"></script>
```

By removing the first /
```
<link rel="stylesheet" href="css/all.css?1460650832631">
<script src="js/shims.js?1460650832626"></script>
<script src="js/app.js?1460650832628"></script>
```

**Comment by d3viant0ne** [comment]
@JMSantos94 

Windows file system semantics ftw.

If you wanted to fix this elsewhere, you should be able to override ```APP_BASE``` in ./tools/config/project.config.ts and just pass it an empty string. This mac is new so I don't have a Windows 10 vm to test that right now.

So something like ...

```
export class ProjectConfig extends SeedConfig {
  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    this.APP_BASE = '';
    // this.APP_TITLE = 'Put name of your app here';
    let additional_deps: InjectableDependency[] = [
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];

    const seedDependencies = this.NPM_DEPENDENCIES;

    this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);
  }
}
```

**Comment by d3viant0ne** [comment]
Out of curiosity, have you picked up the linux file system changes that Microsoft just released?

**Comment by JMSantos94** [comment]
@d3viant0ne thanks, I will take your suggestions into my project.
To be honest, I am not aware of Microsoft's releases.
I personally use Mac, but in the office they gave me a windows desktop.

**Comment by d3viant0ne** [comment]
I'll pull down a Windows 10 iso this evening and see if I can find a fix for this as opposed to the hacky work around I suggested.

**Comment by JMSantos94** [comment]
@d3viant0ne appreciate it. There are not hurries, so take as much time as you need. Thanks!

**Comment by nulldev07** [comment]
I see this happening only when you open it up from the file system(for e.g. on double clicking the index.html).

If I host it on a server, everything works fine.

**Comment by d3viant0ne** [comment]
@JMSantos94 - Is that webstorm you are trying to do all this in ?

**Comment by d3viant0ne** [comment]
And if so, can you try just running npm run serve.dev / npm run serve.prod from the commandline

**Comment by OlivierMary** [comment]
Hi,

I'm on windows 10 and no problem for me with `npm start` or `npm run serve.prod`.

But on double-click on `dist/prod/index.html` I got the same console log than @JMSantos94 like @nulldev07 

Can we launch the index.html like that on unix system ?

**Comment by JMSantos94** [comment]
@d3viant0ne @nulldev07 

Yes, my bad. I was trying to email my changes to some of my co-workers without technical background. 

Thanks a lot everyone, and appreciate the quick responses =)
Have a great weekend!

**Comment by rodolfocop** [comment]
Hi everyone,

I'm with @jvitor83 using "windows 10 and IIS" in the company where we work and we go through problems with seed due to sub-systems.

My suggestion so that other people using the same SO, can solve.

I have the following scenario:

Main application: www.site.com
Another application: www.site.com/subsite/

Problems found:

1 Any change in the "APP_BASE" in "SeedConfig class" modified the addresses of files *.js and *.css, getting always pointing to a subdomain more than I had

 1.1 - APP_BASE = argv['base'] || '/Subsite'; Generated the following url: www.site.com/subsite/#/subsite/ - She had no problems, but it is not correct.

2 Another option was to change the addresses of the script via files, as found here on an issue "npm run build.prod -- --env=prod --app-env=build.dev --dest=subsite --base=/subsite/ "and change the <base href ="<%=APP_BASE%> "> to <base href ="/">
  2.1 This would be the best option because the project would be with APP_BASE pointing to my "subsite" and define "base url" as '/', making this option had the following problem.
   2.1.1 Access Url: www.site.com/subsite/# was changed to www.site.com/#/subsite/ being impossible to access the functionality when it was accessed directly (Save to favorites), he tried to access a route Main application of "www.site.com/#" where not met and redirected to the page 404.


Solution:

The only solution we found after this test was because the idea of ​​@JMSantos94 still was unusual make changes manually always put work properly.

At that moment changed again the variable APP_BASE = argv ['base'] || '' <- No parameter.

It worked properly, without presenting any of the above reported problems.

I believe it can solve many of the problems with sub-systems that can appear in Windows.

Thank you all for your help.
