### ISSUE TITLE
Migrate to csso from cssnano

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#773]
Here is a [slide deck for CSSO](https://github.com/css/csso) which can be used as reference.

Based on the benchmarks we get great compression and better performance.

**Comment by d3viant0ne** [comment]
@mgechev - I tinkered with it a bit and came up with similar results. Took about a second off my build and the payload was definitely smaller. 

If nobody else gets to this, i'll do it this weekend.

**Comment by Shyam-Chen** [comment]
There is something that `csso` does not have.

[cssnano optimisations](http://cssnano.co/optimisations/)

**Comment by mgechev** [comment]
@Shyam-Chen which optimization fro cssnano is missing in csso?

**Comment by Shyam-Chen** [comment]
@mgechev 
1. convert time & length values
2. discard outdated vendor prefixes
3. reduce transform functions
4. minimise gradient parameters
5. **The rest is not safe.**

**Comment by mgechev** [comment]
Okay, lets put that on hold for now.

**Comment by lahmatiy** [comment]
@Shyam-Chen 
> 1. convert time & length values
> 3. reduce transform functions
> 4. minimise gradient parameters

In practice, it gives insignificant saving.

> 2. discard outdated vendor prefixes

It's achieved by using `autoprefixer` and you're already using it. So `cssnano` does nothing in this case.

> 5. The rest is not safe.

Unsafe optimisations is not good enough for common cases. Especially when using for production only. Since it can breaks something that can be hard to figure out exactly what, especially in large projects. Also `cssnano` has a note about it:

> Note that cssnano enables aggressive optimisations by default, which might not always be what you want. Set options.safe to true if you want to disable this. In future versions, only safe options will be enabled by default, starting from version 4.

Truly speaking every CSS minifier is not safe currently. And each of them has some unique optimizations. Yep, `csso` has no some specific optimisations that `cssnano` has and vice versa.
Currently `csso` doesn't focus on optimizations that save insignificant bytes in rare cases. Instead of this it introduces advanced optimizations (e.g. [usage data](https://github.com/css/csso#usage-data)) that can save much more bytes. In our case those optimisations allow us to reduce CSS more than twice (in particular for our project from 600Kb to 230Kb).
In addition `csso` much faster than `cssnano` – 10-100 times on real projects. It's also important as the time changes depending on the size of project. For example in our project, CSS increased from ~600Kb to ~800Kb in 5 months. Time changed for `cssnano` 23s → 48s, for `csso` 0.5s → 0.63s. Believe it makes sense. You can also try to use [postcss-csso](https://github.com/lahmatiy/postcss-csso) as an alternative to `cssnano`.
Just FYI.

I see `clean-css` in pipeline. Using of two CSS minifiers in one pipeline looks odd. `clean-css` is fast enough. But transforming CSS by two minifiers might leads to "nobody knows what is going wrong" (besides performance issues because of parse-translate CSS all the time along pipeline).

**Comment by Shyam-Chen** [comment]
//cc @mgechev @d3viant0ne

**Comment by d3viant0ne** [comment]
> In practice, it gives insignificant saving.

I have to agree here. Even on my largest client side application, the benefits in payload size done warrant the issues that crop up with super aggressive optimizations.

To @lahmatiy's second point, I personally use csso at it's default settings during development and enable it's advanced optimizations when I have a stable product to get the reductions in payload size that matter.

I've implemented csso using postcss-csso and have been happy with it. Given that we have already implemented postcss, adding the postcss-csso plugin is probably the route that makes the most sense and has the benefit of making the implementation super easy.

It would also allow for the removal of the clean-css task entirely which saves a second or so in the change detection cycle.
