### ISSUE TITLE
New BROWSER_SYNC_CONFIG says its serving from wrong folder

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#785]
Not high priority but just thought I would point this out.  There was some new changed done to how browser sync works where the **BROWSER_SYNC_CONFIG** was added to the **seed.config.ts** file.  In there, it says the base dir is `${this.DIST_DIR}/empty/` which also is printed in the termnial by saying:

> [BS] Serving files from: dist/empty/

However, the dev is still serving from dist/dev as before and prod is from dist/prod.  

Could it be updated to reflect the correct folder it is serving from to avoid any confusion?

**Comment by njs50** [comment]
technically it is serving from /empty/, it just has a route added for / -> dist/dev or whatever. 

it's a bit of a hack because browser sync doesn't let you have an empty root dir, which you need when using --base. 

previously there were two configs one for when --base was / and one for when it was /something/, now it's using the same config for both.

I wonder if it's worth swapping browser sync out for express (which we are already using) + live reload to reduce the deps/complexity. Do people actually use browser sync to keep multiple browsers in sync or do they mostly use it for the live reload?

**Comment by mpetkov** [comment]
I only use it for live reload.  I doubt people are using the browser sync option since there is such a big push on doing automated testing.

**Comment by mgechev** [comment]
BrowserSync doesn't have good integration with zones yet, so we're mostly using it because it provides live-reload out of the box and allows easy setup for using two base directories.

**Comment by d3viant0ne** [comment]
Personally, I've only used it for local live reload. The sync functions are cool but most of my cross browser stuff is automated like @mpetkov mentioned.

**Comment by ludohenin** [comment]
I think we can close that one.
This is done intentionally (hack) to avoid serving anything from project root.
