### ISSUE TITLE
After SASS integration - Errors and Reloading browser

### ISSUE THREAD

**Issue by katalonne** [mgechev/angular2-seed#943]
After following the SASS Support Integration instructions, I get a lot of (stupid) errors when building the project :
![ng2-errors](https://cloud.githubusercontent.com/assets/12927805/15647695/e590be04-266d-11e6-934d-ec1e3e37235e.png)

Everything was fine before integrating Sass...
I get errors like:
**file should end with a newline**
**trailing whitespace**
and more...

Furthermore, when I make changes In any component and save them, I get :
**[BS] Reloading Browsers...**
And it stays so forever. It doesn't reload.

What can I do?

**Comment by mgechev** [comment]
These are style errors that you can fix - remove the trailing spaces, unused variables, add newlines in the end of the files and do not leave empty blocks.

**Comment by katalonne** [comment]
fd

**Comment by katalonne** [comment]
No, these are stupid errors!!!!

Let just be rational, and think that this are not programming language (Javascript) conventions,

**Comment by Sjiep** [comment]
@katalonne The errors refer to have nothing to do with you enabling SASS because they are pointing towards your Angular2 service files. I.e. they are TSLint errors. The tslint config followings the [Angular2 Style Guide](https://angular.io/styleguide) as close as possible.

If you so desire to have a different configurations, feel free to edit the `tslint.json` file which you can find in the root directory of the project.

**Comment by katalonne** [comment]
Dude, This errors showed up after I integrated sass!!!
