### ISSUE TITLE
 Error on fetch for angular2-jwt.js

### ISSUE THREAD

**Issue by Rademanc** [mgechev/angular2-seed#990]
Hi.
I am having trouble including angular2-jwt in my production build.
Why would it be looking for  angular2-jwt.js in the root node_modules directory?
Dev build works fine. Any ideas?

[14:51:29] 'build.bundles.app' errored after 1.08 s
[14:51:29] Error on fetch for angular2-jwt.js at file:///C:/dev/Backups/angular2-seed/node_modules/angular2-jwt.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'C:\dev\Backups\angular2-seed\node_modules\angular2-jwt.js'
    at Error (native)

**Comment by mgechev** [comment]
The SystemJS mapping that you have (or haven't) provided is incorrect.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the seed works.

**Comment by Rademanc** [comment]
Thanks.
